---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define ntp_packages.
  set_fact:
    ntp_packages: "{{ __ntp_packages | list }}"
  when: ntp_packages is not defined

- name: Define ntp_daemon.
  set_fact:
    ntp_daemon: "{{ __ntp_daemon }}"
  when: ntp_daemon is not defined
